import React, { useState } from 'react';
import { Check, Copy, Database, ShieldCheck } from 'lucide-react';
import { evaluateDatabaseRequirements } from '@/services/dbIntelligence';
import { DatabaseDecision } from '@/types';

export const DatabaseStudioView: React.FC = () => {
  const [name,setName]=useState('');
  const [requirements,setRequirements]=useState('');
  const [decision,setDecision]=useState<DatabaseDecision|null>(null);
  const [copied,setCopied]=useState(false);
  const run=()=>{if(name.trim()||requirements.trim()) setDecision(evaluateDatabaseRequirements(name.trim()||'Untitled project',requirements));};
  const copy=()=>{const sql=decision?.generatedMigrations?.[0]?.sql;if(!sql)return;navigator.clipboard.writeText(sql);setCopied(true);setTimeout(()=>setCopied(false),1500);};
  return <div className="h-full overflow-y-auto p-5 md:p-8"><div className="max-w-6xl mx-auto space-y-6">
    <header><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-zinc-500"><Database size={15}/> Data architecture</div><h1 className="mt-2 text-2xl md:text-3xl font-black tracking-tight">Database</h1><p className="mt-1 text-sm text-zinc-500">Analyze a project before provisioning data infrastructure.</p></header>
    <section className="bg-white border border-zinc-200 rounded-2xl p-5 space-y-3"><div className="grid md:grid-cols-3 gap-3"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Project name" className="border border-zinc-200 rounded-xl px-3 py-2 text-sm"/><textarea value={requirements} onChange={e=>setRequirements(e.target.value)} placeholder="Describe users, data, auth, payments, files, or other requirements" className="md:col-span-2 border border-zinc-200 rounded-xl px-3 py-2 text-sm min-h-20 resize-y"/></div><button onClick={run} className="px-4 py-2 rounded-xl bg-zinc-950 text-white text-sm font-semibold">Analyze</button></section>
    {decision && <><section className="grid md:grid-cols-3 gap-3"><div className="bg-white border border-zinc-200 rounded-2xl p-4"><div className="text-xs text-zinc-500">Database</div><div className="mt-2 font-black text-lg">{decision.databaseRequired?'Required':'Not required'}</div><p className="text-xs text-zinc-500 mt-1">{decision.reason}</p></div><div className="bg-white border border-zinc-200 rounded-2xl p-4"><div className="text-xs text-zinc-500">Provider</div><div className="mt-2 font-black text-lg">{decision.recommendedProvider}</div><p className="text-xs text-zinc-500 mt-1">{decision.requiredServices.join(' · ')||'No additional services'}</p></div><div className="bg-white border border-zinc-200 rounded-2xl p-4"><div className="text-xs text-zinc-500">Roles</div><div className="mt-2 font-black text-lg">{decision.projectRbacRoles.length||0}</div><p className="text-xs text-zinc-500 mt-1">{decision.projectRbacRoles.join(' · ')||'None detected'}</p></div></section>
    {decision.suggestedSchema.length>0 && <section className="bg-white border border-zinc-200 rounded-2xl p-5"><h2 className="font-bold">Schema</h2><div className="mt-4 grid md:grid-cols-2 gap-3">{decision.suggestedSchema.map(t=><div key={t.tableName} className="border border-zinc-200 rounded-xl p-4"><div className="flex items-center justify-between"><span className="font-semibold text-sm">{t.tableName}</span><ShieldCheck size={15} className="text-emerald-600"/></div><p className="text-xs text-zinc-500 mt-1">{t.description}</p><div className="flex flex-wrap gap-1 mt-3">{t.columns.map(c=><span key={c} className="text-[10px] font-mono bg-zinc-100 rounded-md px-2 py-1">{c}</span>)}</div><p className="text-[11px] text-zinc-500 mt-3">RLS: {t.rlsPolicy}</p></div>)}</div></section>}
    {decision.generatedMigrations[0] && <section className="bg-zinc-950 rounded-2xl p-5 text-zinc-200"><div className="flex items-center justify-between"><div><h2 className="font-bold text-sm">{decision.generatedMigrations[0].filename}</h2><p className="text-xs text-zinc-500 mt-1">Migration SQL</p></div><button onClick={copy} className="px-3 py-1.5 rounded-lg bg-zinc-800 text-xs">{copied?<><Check size={12} className="inline mr-1"/>Copied</>:<><Copy size={12} className="inline mr-1"/>Copy SQL</>}</button></div><pre className="mt-4 text-[11px] leading-relaxed overflow-auto max-h-96">{decision.generatedMigrations[0].sql}</pre></section>}</>}
  </div></div>;
};